[package]
name = "minijam-work-package-builder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bounded-collections.workspace = true
cid.workspace = true
jam-codec = { version = "0.1.1", default-features = false }
jambda-refine = { path = "../../external/jambda/crates/refine", default-features = false }
jp-core-primitives = { path = "../../external/jambda/crates/core-primitives", default-features = false }
minijam-protocol = { path = "../minijam-protocol", default-features = false }
multihash.workspace = true
thiserror.workspace = true

[features]
default = ["std"]
std = [
  "jam-codec/std",
  "jambda-refine/std",
  "jp-core-primitives/std",
  "minijam-protocol/std",
]
