[package]
name = "minijam-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true
frame-system-rpc-runtime-api.workspace = true
pallet-aura.workspace = true
pallet-balances.workspace = true
pallet-grandpa.workspace = true
pallet-minijam = { path = "../pallets/minijam", default-features = false }
pallet-minijam-workers = { path = "../pallets/minijam-workers", default-features = false }
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
pallet-transaction-payment.workspace = true
pallet-transaction-payment-rpc-runtime-api.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
sp-api.workspace = true
sp-block-builder.workspace = true
sp-consensus-aura = { workspace = true, features = ["serde"] }
sp-consensus-grandpa = { workspace = true, features = ["serde"] }
sp-core = { workspace = true, features = ["serde"] }
sp-genesis-builder.workspace = true
sp-inherents.workspace = true
sp-keyring.workspace = true
sp-offchain.workspace = true
sp-runtime = { workspace = true, features = ["serde"] }
sp-session.workspace = true
sp-transaction-pool.workspace = true
sp-version = { workspace = true, features = ["serde"] }

[build-dependencies]
substrate-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-minijam-workers/std",
  "pallet-minijam/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "serde_json/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-consensus-grandpa/std",
  "sp-core/std",
  "sp-genesis-builder/std",
  "sp-inherents/std",
  "sp-keyring/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "substrate-wasm-builder",
]
runtime-benchmarks = []
try-runtime = []
