[package]
name = "pallet-minijam"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
frame-support.workspace = true
frame-system.workspace = true
minijam-protocol = { path = "../../crates/minijam-protocol", default-features = false }
minijam-jamcore-api = { path = "../../crates/minijam-jamcore-api", default-features = false }
minijam-state-adapter = { path = "../../crates/minijam-state-adapter", default-features = false }
pallet-minijam-workers = { path = "../minijam-workers", default-features = false }
parity-scale-codec.workspace = true
scale-info.workspace = true
sp-runtime.workspace = true

[dev-dependencies]
pallet-balances = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }

[features]
default = ["std"]
std = [
  "frame-support/std",
  "frame-system/std",
  "minijam-jamcore-api/std",
  "minijam-state-adapter/std",
  "minijam-protocol/std",
  "pallet-minijam-workers/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "sp-runtime/std",
]
