[package]
name = "minijam-playground-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
cid.workspace = true
jam-codec = { version = "0.1.1", default-features = false }
jp-core-primitives = { path = "../../external/jambda/crates/core-primitives", default-features = false }
minijam-chain-client = { path = "../minijam-chain-client" }
minijam-compiler-api = { path = "../minijam-compiler-api" }
minijam-protocol = { path = "../minijam-protocol" }
minijam-runtime = { path = "../../runtime" }
minijam-work-package-builder = { path = "../minijam-work-package-builder" }
parity-scale-codec.workspace = true
pallet-minijam = { path = "../../pallets/minijam" }
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sp-core = { workspace = true, default-features = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
jambda-refine = { path = "../../external/jambda/crates/refine" }
tempfile.workspace = true
tower = { version = "0.5.2", features = ["util"] }

[[bin]]
name = "minijam-playground-api"
path = "src/main.rs"
