[package]
name = "minijam-bridge-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
minijam-protocol = { path = "../minijam-protocol", default-features = false }
parity-scale-codec.workspace = true

[features]
default = ["std"]
std = ["minijam-protocol/std", "parity-scale-codec/std"]
