[package]
name = "minijam-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
clap = { workspace = true, features = ["derive"] }
futures.workspace = true
jsonrpsee = { workspace = true, features = ["ws-client"] }
minijam-protocol = { path = "../minijam-protocol" }
minijam-worker-engine = { path = "../minijam-worker-engine" }
parity-scale-codec.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["std"] }
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
