[package]
name = "minijam-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
clap = { workspace = true, features = ["derive"] }
futures.workspace = true
jam-codec = { version = "0.1.1", default-features = false }
jambda-minijam-executive = { path = "../../external/jambda/crates/minijam-executive", features = ["std"] }
jambda-refine = { path = "../../external/jambda/crates/refine", default-features = false }
jambda-state-backend = { path = "../../external/jambda/crates/state-backend" }
jp-core-primitives = { path = "../../external/jambda/crates/core-primitives", default-features = false }
jp-vm-engine = { path = "../../external/jambda/vm/engine", features = ["std"] }
jp-vm-interp = { path = "../../external/jambda/vm/interp", features = ["std"] }
jsonrpsee = { workspace = true, features = ["ws-client"] }
minijam-protocol = { path = "../minijam-protocol" }
minijam-runtime = { path = "../../runtime" }
minijam-worker-engine = { path = "../minijam-worker-engine" }
pallet-minijam-workers = { path = "../../pallets/minijam-workers" }
parity-scale-codec.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["std"] }
sp-core = { workspace = true, default-features = true }
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
